language: generic
sudo: false

before_install:
- chmod +x ./.travis-package.sh

script:
- "./.travis-package.sh"

deploy:
  provider: releases
  api_key:
    secure: XX48jSZ/AChWwC+V4ONiOxGGdOxmhDtFsjuexAVMXp2NUOmCzCa135OIR/OgxYIKMg/JVhmQ28rh1qoKtpaIT28g9VmRC65ZG8G/yI5PasTSBozImB1sCTM7kHKmcxQJKoA1Nhc58Ok2T/5azGelKddY8hZf1/7EbrkhPO2Bu/UCOZyXId2Xt0LGdMb0gSbyVesGmGOvyOWUCoaqyQ91pLCbfH6drtxHZCG7i33BwVYQU0yQil6463Up9bEEIM25A9H62xQC5T+9DOWMwsJGYMHlNh1Kt41LNodthuTzgRyfwOGrW4FcrylXHvMpW9vfneTqUlI7YR3/6NgpcOEwA/YO1G5m5klT7zPk8SNB8e4oDGOZu52DK+cl62Xbg/wuhZcN27hfNFdQ+YQLuvjtifIr1e4F+YV/iZ97US+orVqG9KbznBwPXB0fbkKmKlCeVsiKHZ19qb6TMnSqCf9kxkWXMxwejbZ+wVPp2FeAsKXEAiR0MxenmncxVV7vq05WsxoY6w4JmGC11QVqNVrFRAG0ZEFcyELj9PYMiAvhk4AwxjSXYTy7sJXCu+PrmjooLwtmCNHY3YWCRrOefTqyIb1quY605L42MpR5kvkvJSShnO9RL5jwhVx2k19X3eaDL5KojdifUNZHqhcLVaEUsplSYlptE6IP9jDv+3zb8+o=
  file: colortools-${TRAVIS_TAG#v}.zip
  skip_cleanup: true
  on:
    tags: true
    repo: pvinis/colortools
