language: generic
sudo: false

before_install:
  - chmod +x ./.travis-package.sh

script:
  - ./.travis-package.sh

deploy:
  provider: releases
  api_key:
    secure: r4nVARB0vP4wDN5TnSol+PYjd1Xl/cHS+GnygQpi6bcpJqnnv7lUt8CqR08qZkkKItninKkHPPKOn/GMFCFCLpzW1o5UIFjQEGeGeAecpCWeYgYjz6GZwK/qAxP9g3DZ8cNIcd8EweV6YZ3TLUxyBNCG8dqRhkLTO/aMphh8iZoz4eDOq8/brOOq3KnDVDODU3/9cgc3CsB+RYgsqMVNOQBFDnMG1RqWi0xSZ5zQeoVejkzvBfzsT+ZR82AXDQ9Wyfr17c7yAMm+Mf0z1+prfJCWorDzMXLxgQMjRaautV/3xYytLCwL28c1u4D4BhROn4T0bV6Id1FgD1PUjr5Cn6nEdyByqK2F9j6Y46ZlhYYT8hUNi+mbU5pUaf4lHljv/K47sporDbs9+NnbvzDNs0H0EJ/rYp0row1PIEEdHpzpdajjpH22sjUwx720jozC3yk7TuW3K/APg/pz+iDY7u0n3koYJ1VUCCIWtemGmYaYV5t6B0fH8e5VBrpLoeas42EMvEGzQG7Ji7UnWWhz56sxPDgSOy+XC4JGN3EIoKlhAke9KrOecBmb6OtTVYGqyr3YWvoPYJHmgHYm2iw6CSjLOOJFP9fgkObCI2OjMEu4aLkgveaKTBaVOpjP0QrTOGU+Y/2hr63xIunE9t6ufmSYS9nlGemTkuCFuPBqZSs=
  file: colortools-${TRAVIS_TAG#v}.zip
  skip_cleanup: true
  on:
    tags: true
    repo: pvinis/colortools
